
 
记录时间：2016-02-02 13:40:45,581 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:352279cb-4994-471a-a287-829b3bb751bd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 13:40:45,644 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:352279cb-4994-471a-a287-829b3bb751bd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 13:40:45,690 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:352279cb-4994-471a-a287-829b3bb751bd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 13:50:45,502 
线程ID:[6] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 13:50:45,533 
线程ID:[6] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 13:50:45,565 
线程ID:[6] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:00:45,443 
线程ID:[6] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:00:45,474 
线程ID:[6] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:00:45,521 
线程ID:[6] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:09:17,428 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:09:18,566 
线程ID:[10] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 没有终结点在侦听可以接受消息的 http://weixin-test.kemai.com.cn/KMMicro_WCF/OfflineMarketingService.svc。这通常是由于不正确的地址或者 SOAP 操作导致的。如果存在此情况，请参见 InnerException 以了解详细信息。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   在 System.Net.HttpWebRequest.GetRequestStream()
   在 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   在 System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 Kemai.O2O.WCF.OperationInvoker.HandleException(Exception ex, ICommunicationObject channel)
   在 Kemai.O2O.WCF.OperationInvoker.Invoke[TChanne,TResult](Func`2 serviceInvocation, TChanne channel)
   在 Kemai.O2O.WCF.OperationInvoker`1.Invoke[TResult](Func`2 serviceInvocation)
   在 Kemai.MSG.Business.MarketingLogic.GetMaketing(CustomerConfig model)
   在 Kemai.MSG.Assistant.MainForm.maketingTime_Elapsed(Object sender, ElapsedEventArgs e)

 
记录时间：2016-02-02 14:09:38,488 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 无法连接到 net.tcp://weixin-test.kemai.com.cn:16901/KMMicro_WCF/MicroDuplexService.svc。连接尝试持续了 00:00:20 时间跨度。TCP 错误代码 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:16901。 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:16901
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonIn(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:09:48,488 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:09:52,061 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 无法连接到 net.tcp://weixin-test.kemai.com.cn:16901/KMMicro_WCF/MicroDuplexService.svc。连接尝试持续了 00:00:03.5724063 时间跨度。TCP 错误代码 10061: 由于目标计算机积极拒绝，无法连接。 218.244.130.253:16901。 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 218.244.130.253:16901
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonIn(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:10:02,076 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:10:10,531 
线程ID:[10] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 没有终结点在侦听可以接受消息的 http://weixin-test.kemai.com.cn/KMMicro_WCF/OfflineMarketingService.svc。这通常是由于不正确的地址或者 SOAP 操作导致的。如果存在此情况，请参见 InnerException 以了解详细信息。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   在 System.Net.HttpWebRequest.GetRequestStream()
   在 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   在 System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 Kemai.O2O.WCF.OperationInvoker.HandleException(Exception ex, ICommunicationObject channel)
   在 Kemai.O2O.WCF.OperationInvoker.Invoke[TChanne,TResult](Func`2 serviceInvocation, TChanne channel)
   在 Kemai.O2O.WCF.OperationInvoker`1.Invoke[TResult](Func`2 serviceInvocation)
   在 Kemai.MSG.Business.MarketingLogic.GetMaketing(CustomerConfig model)
   在 Kemai.MSG.Assistant.MainForm.maketingTime_Elapsed(Object sender, ElapsedEventArgs e)

 
记录时间：2016-02-02 14:10:20,640 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 无法连接到 net.tcp://weixin-test.kemai.com.cn:16901/KMMicro_WCF/MicroDuplexService.svc。连接尝试持续了 00:00:18.5640326 时间跨度。TCP 错误代码 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:16901。 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:16901
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonIn(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:10:30,641 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:19:55,825 
线程ID:[1] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Kemai.MSG.Business.WeChatLogic.MicropayCall_wx(WXPayRequest payRequest)
   在 Kemai.MSG.Implements.AbstractService.MicropayCall_wx(String xml, String sign)

 
记录时间：2016-02-02 14:20:44,406 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:20:44,593 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:20:44,624 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:c5aca168-60c8-4fbb-99ee-9921b6da5700
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:27:27,137 
线程ID:[1] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.ServerTooBusyException: 位于 http://weixin-test.kemai.com.cn/KMMicro_WCF/PayServices.svc 的 HTTP 服务不可用。这可能是因为该服务太忙，或是因为未找到侦听指定地址的终结点。请确保地址正确，并在稍后再次尝试访问该服务。 ---> System.Net.WebException: 远程服务器返回错误: (503) 服务器不可用。
   在 System.Net.HttpWebRequest.GetResponse()
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   在 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 Kemai.MSG.Business.WeChatLogic.MicropayCall_wx(WXPayRequest payRequest)
   在 Kemai.MSG.Implements.AbstractService.MicropayCall_wx(String xml, String sign)

 
记录时间：2016-02-02 14:28:02,208 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:28:18,744 
线程ID:[23] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 没有终结点在侦听可以接受消息的 http://weixin-test.kemai.com.cn/KMMicro_WCF/OfflineMarketingService.svc。这通常是由于不正确的地址或者 SOAP 操作导致的。如果存在此情况，请参见 InnerException 以了解详细信息。 ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   在 System.Net.HttpWebRequest.GetRequestStream()
   在 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   在 System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 Kemai.O2O.WCF.OperationInvoker.HandleException(Exception ex, ICommunicationObject channel)
   在 Kemai.O2O.WCF.OperationInvoker.Invoke[TChanne,TResult](Func`2 serviceInvocation, TChanne channel)
   在 Kemai.O2O.WCF.OperationInvoker`1.Invoke[TResult](Func`2 serviceInvocation)
   在 Kemai.MSG.Business.MarketingLogic.GetMaketing(CustomerConfig model)
   在 Kemai.MSG.Assistant.MainForm.maketingTime_Elapsed(Object sender, ElapsedEventArgs e)

 
记录时间：2016-02-02 14:28:23,237 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 无法连接到 net.tcp://weixin-test.kemai.com.cn:16901/KMMicro_WCF/MicroDuplexService.svc。连接尝试持续了 00:00:20 时间跨度。TCP 错误代码 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:16901。 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:16901
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonIn(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:28:33,252 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:28:34,345 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 无法连接到 net.tcp://weixin-test.kemai.com.cn:16901/KMMicro_WCF/MicroDuplexService.svc。连接尝试持续了 00:00:01.0930020 时间跨度。TCP 错误代码 10061: 由于目标计算机积极拒绝，无法连接。 218.244.130.253:16901。 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 218.244.130.253:16901
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonIn(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:28:44,361 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:29:04,984 
线程ID:[1] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonOut(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.LogOut()

 
记录时间：2016-02-02 14:29:05,015 
线程ID:[11] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.TimeoutException: 打开操作没有在分配的超时 00:00:20 内完成。分配给此操作的时间可能已经是更长超时的一部分。 ---> System.TimeoutException: 套接字传输在 00:00:10.9363841 之后超时。超过了绑定上设置的超时。分配给此操作的时间可能已经是更长超时的一部分。 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
   在 System.ServiceModel.Channels.SocketConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   在 System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   在 System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonIn(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-02-02 14:29:28,635 
线程ID:[1] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonOut(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.LogOut()

 
记录时间：2016-02-02 14:30:46,092 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:bc253340-cbf1-4bce-a013-05cf23a04763
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:30:46,528 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:bc253340-cbf1-4bce-a013-05cf23a04763
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:30:46,560 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:bc253340-cbf1-4bce-a013-05cf23a04763
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:40:44,929 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:40:44,965 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:40:45,003 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:43:25,458 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_Pr_get_cashno'。
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   在 System.Data.SqlClient.SqlDataReader.get_MetaData()
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   在 System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   在 System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   在 System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   在 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   在 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   在 Kemai.MSG.Common.Data.DbHelperSQL.ExecuteDataset(SqlConnection connection, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   在 Kemai.MSG.Common.Data.DbHelperSQL.ExecuteDataset(CommandType commandType, String commandText, SqlParameter[] commandParameters)
   在 Kemai.MSG.DataAccess.ItemDal.GetCashNoList()
   在 Kemai.MSG.Business.MallLogic.GetCashNoList()
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:50:45,002 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:50:45,049 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:50:45,080 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 14:52:49,133 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 过程或函数 'kmmicro_Pr_set_fillmoney' 需要参数 '@encryptBalance'，但未提供该参数。
   在 Kemai.MSG.DataAccess.VipDal.FillMoneyToBranch(String vip_no, Decimal fillmoney, Decimal giveamount, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.FillMoneyToBranch(String vip_no, Decimal fillmoney, Decimal giveamount, String sheetNo)
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:201,State:4,Class:16

 
记录时间：2016-02-02 14:58:38,400 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 过程或函数 'kmmicro_Pr_set_fillmoney' 需要参数 '@encryptBalance'，但未提供该参数。
   在 Kemai.MSG.DataAccess.VipDal.FillMoneyToBranch(String vip_no, Decimal fillmoney, Decimal giveamount, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.FillMoneyToBranch(String vip_no, Decimal fillmoney, Decimal giveamount, String sheetNo)
ClientConnectionId:a0600133-ff7a-4590-bcd9-86b5739803b6
Error Number:201,State:4,Class:16

 
记录时间：2016-02-02 15:00:41,350 
线程ID:[1] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ObjectDisposedException: 无法访问已释放的对象。
对象名:“System.ServiceModel.Channels.ServiceChannel”。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonOut(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.LogOut()

 
记录时间：2016-02-02 15:10:45,113 
线程ID:[8] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:10:45,160 
线程ID:[8] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:10:45,191 
线程ID:[8] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:20:45,178 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:20:45,225 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:20:45,240 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:30:45,174 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:30:45,205 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:30:45,236 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:40:45,211 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:40:45,243 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:40:45,276 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:50:45,218 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:50:45,249 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 15:50:45,280 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:dcb14a8e-599b-478f-aaad-5ab83e2eeafd
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:00:45,263 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:0b164f6a-3947-491e-bbd7-9818d7808f09
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:00:45,325 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:0b164f6a-3947-491e-bbd7-9818d7808f09
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:00:45,357 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:0b164f6a-3947-491e-bbd7-9818d7808f09
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:20:45,325 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:0931368f-b3e3-4aab-a2db-a2156a9a6d99
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:20:45,372 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:0931368f-b3e3-4aab-a2db-a2156a9a6d99
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:20:45,418 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:0931368f-b3e3-4aab-a2db-a2156a9a6d99
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:30:45,337 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4f5e547b-d7f9-4703-9585-085f4d8f25a8
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:30:45,384 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4f5e547b-d7f9-4703-9585-085f4d8f25a8
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:30:45,415 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4f5e547b-d7f9-4703-9585-085f4d8f25a8
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:40:45,379 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4f5e547b-d7f9-4703-9585-085f4d8f25a8
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:40:45,426 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4f5e547b-d7f9-4703-9585-085f4d8f25a8
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:40:45,457 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4f5e547b-d7f9-4703-9585-085f4d8f25a8
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:50:45,340 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:50:45,403 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 16:50:45,434 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:00:45,399 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:00:45,431 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:00:45,462 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:01:54,354 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904):  
   在 Kemai.MSG.DataAccess.VipDal.RegisterVip(String name, String mobile, String sex, DateTime birthday, String pwd, String openId)
   在 Kemai.MSG.Business.MemberLogic.RegisterVip(String name, String mobile, String sex, String pwd, String birthday, String openId)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:50000,State:1,Class:16

 
记录时间：2016-02-02 17:01:59,268 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904):  
   在 Kemai.MSG.DataAccess.VipDal.RegisterVip(String name, String mobile, String sex, DateTime birthday, String pwd, String openId)
   在 Kemai.MSG.Business.MemberLogic.RegisterVip(String name, String mobile, String sex, String pwd, String birthday, String openId)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:50000,State:1,Class:16

 
记录时间：2016-02-02 17:02:12,435 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904):  
   在 Kemai.MSG.DataAccess.VipDal.RegisterVip(String name, String mobile, String sex, DateTime birthday, String pwd, String openId)
   在 Kemai.MSG.Business.MemberLogic.RegisterVip(String name, String mobile, String sex, String pwd, String birthday, String openId)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:50000,State:1,Class:16

 
记录时间：2016-02-02 17:10:45,367 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:10:45,398 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:10:45,429 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:20:45,394 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:20:45,425 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:20:45,456 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:30:45,467 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:30:45,499 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:30:45,530 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:40:45,432 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:40:45,463 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:40:45,494 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:50:45,460 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:50:45,491 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 17:50:45,522 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 18:00:45,453 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 18:00:45,484 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 18:00:45,516 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 18:10:45,484 
线程ID:[21] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 18:10:45,515 
线程ID:[21] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16

 
记录时间：2016-02-02 18:10:45,546 
线程ID:[21] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:4dc16d49-35e4-4473-8055-1be20856c8f9
Error Number:2812,State:62,Class:16
