
 
记录时间：2016-01-22 12:29:39,100 
线程ID:[10] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-01-22 12:30:00,348 
线程ID:[10] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.EndpointNotFoundException: 无法连接到 net.tcp://weixin-test.kemai.com.cn:16901/KMMicro_WCF/MicroDuplexService.svc。连接尝试持续了 00:00:20 时间跨度。TCP 错误代码 10060: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:16901。 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 218.244.130.253:16901
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   在 System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   在 System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   在 System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonIn(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-01-22 12:30:10,363 
线程ID:[10] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-01-22 12:30:27,024 
线程ID:[16] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationException: 基础连接已经关闭: 服务器关闭了本应保持活动状态的连接。 ---> System.Net.WebException: 基础连接已经关闭: 服务器关闭了本应保持活动状态的连接。 ---> System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。 ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetResponse()
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   在 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 Kemai.O2O.WCF.OperationInvoker.HandleException(Exception ex, ICommunicationObject channel)
   在 Kemai.O2O.WCF.OperationInvoker.Invoke[TChanne,TResult](Func`2 serviceInvocation, TChanne channel)
   在 Kemai.O2O.WCF.OperationInvoker`1.Invoke[TResult](Func`2 serviceInvocation)
   在 Kemai.MSG.Business.MarketingLogic.GetMaketing(CustomerConfig model)
   在 Kemai.MSG.Assistant.MainForm.maketingTime_Elapsed(Object sender, ElapsedEventArgs e)

 
记录时间：2016-01-22 13:29:24,860 
线程ID:[10] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-01-22 13:29:27,575 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationException: 基础连接已经关闭: 服务器关闭了本应保持活动状态的连接。 ---> System.Net.WebException: 基础连接已经关闭: 服务器关闭了本应保持活动状态的连接。 ---> System.IO.IOException: 无法从传输连接中读取数据: 您的主机中的软件中止了一个已建立的连接。。 ---> System.Net.Sockets.SocketException: 您的主机中的软件中止了一个已建立的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   在 System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.GetResponse()
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   在 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 Kemai.O2O.WCF.OperationInvoker.HandleException(Exception ex, ICommunicationObject channel)
   在 Kemai.O2O.WCF.OperationInvoker.Invoke[TChanne,TResult](Func`2 serviceInvocation, TChanne channel)
   在 Kemai.O2O.WCF.OperationInvoker`1.Invoke[TResult](Func`2 serviceInvocation)
   在 Kemai.MSG.Business.MarketingLogic.GetMaketing(CustomerConfig model)
   在 Kemai.MSG.Assistant.MainForm.maketingTime_Elapsed(Object sender, ElapsedEventArgs e)

 
记录时间：2016-01-22 14:50:10,440 
线程ID:[15] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.ProtocolException: 响应消息的内容类型 text/html; charset=utf-8 与绑定(application/soap+xml; charset=utf-8)的内容类型不匹配。如果使用自定义编码器，请确保正确实现 IsContentTypeSupported 方法。响应的前 1024 个字节为:“<!DOCTYPE html>
<html>
    <head>
        <title>运行时错误</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px;”。 ---> System.Net.WebException: 远程服务器返回错误: (500) 内部服务器错误。
   在 System.Net.HttpWebRequest.GetResponse()
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- 内部异常堆栈跟踪的结尾 ---

Server stack trace: 
   在 System.ServiceModel.Channels.HttpChannelUtilities.ValidateRequestReplyResponse(HttpWebRequest request, HttpWebResponse response, HttpChannelFactory`1 factory, WebException responseException, ChannelBinding channelBinding)
   在 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   在 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 Kemai.O2O.WCF.OperationInvoker.HandleException(Exception ex, ICommunicationObject channel)
   在 Kemai.O2O.WCF.OperationInvoker.Invoke[TChanne,TResult](Func`2 serviceInvocation, TChanne channel)
   在 Kemai.O2O.WCF.OperationInvoker`1.Invoke[TResult](Func`2 serviceInvocation)
   在 Kemai.MSG.Business.MarketingLogic.GetMaketing(CustomerConfig model)
   在 Kemai.MSG.Assistant.MainForm.maketingTime_Elapsed(Object sender, ElapsedEventArgs e)

 
记录时间：2016-01-22 14:50:20,003 
线程ID:[10] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.Heart(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.<>c__DisplayClass1.<Login>b__0()

 
记录时间：2016-01-22 15:59:28,228 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 15:59:28,306 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 15:59:28,353 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 15:59:28,384 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 15:59:28,431 
线程ID:[3] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:10:37,238 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:10:37,285 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:10:37,332 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:10:37,363 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:10:37,410 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:20:37,242 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:20:37,274 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:20:37,320 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:20:37,352 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:20:37,398 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:885a0ac5-ba5f-4ef8-b54e-13431d4b6050
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:30:37,240 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:30:37,271 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:30:37,318 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:30:37,364 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:30:37,396 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:40:37,250 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:40:37,281 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:40:37,328 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:40:37,359 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:40:37,406 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:50:37,252 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:50:37,283 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:50:37,330 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:50:37,361 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 16:50:37,408 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:b2a51e57-cee4-48fa-9b99-12dcbdc04b3b
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:00:37,245 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:00:37,292 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:00:37,339 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:00:37,386 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:00:37,417 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:10:37,253 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:10:37,299 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:10:37,331 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:10:37,377 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:10:37,409 
线程ID:[19] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.Data.SqlClient.SqlException (0x80131904): 找不到存储过程 'kmmicro_pr_check_vipcostorder'。
   在 Kemai.MSG.DataAccess.VipDal.CheckVipCostOrder(String vip_no, String sheetNo)
   在 Kemai.MSG.Business.MemberLogic.CheckVipCostOrder(String vip_no, String sheetNo)
ClientConnectionId:6e34f2f9-78db-4633-92b7-9c0a723eb18a
Error Number:2812,State:62,Class:16

 
记录时间：2016-01-22 17:12:39,901 
线程ID:[1] 
日志级别：ERROR 
出错类：RollingLogFileAppender property: [(null)] - 
错误描述：System.ObjectDisposedException: 无法访问已释放的对象。
对象名:“System.ServiceModel.Channels.ServiceChannel”。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Kemai.O2O.Contract.IToOnlineService.LogonOut(String branchKey)
   在 Kemai.MSG.Business.ClientLogin.LogOut()
